
#:schema node_modules/wrangler/config-schema.json
name = "oz-vin-check"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "oz-vin-check-db"
database_id = "xxxx-xxxx-xxxx-xxxx" # User to fill
